version: "3"

networks:
  traefik_reverse_proxy:
    external: true

services:
  node:
    image: node:alpine
    restart: always
    # expose:
      # - 3000
    # depends_on:
    #   - mongo
    #   - redis
    volumes:
      - ../server:/srv
    # user: node
    working_dir: /srv
    networks:
      - byzantine
    environment:
       - NODE_ENV=production
    env_file:
      - ../server/.env
    command: npm run start
    command: >
        sh -c "npm install sqlite && npm run start"
    tty: true
    # environment:
    #   - REDIS_URL=redis://byzantine_redis_1
    #   - MONGO_URL=mongodb://byzantine_mongo_1/byzantine-dev
    # entrypoint: "./wait-for-it.sh byzantine_mongo_1:27017"

  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - traefik_reverse_proxy
      - byzantine
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ../client/dist:/etc/nginx/html
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_reverse_proxy
      - traefik.http.routers.byzantine.rule=Host(`TODO`)
      - traefik.http.routers.byzantine.entrypoints=web_entrypoint
      - traefik.http.routers.byzantine.middlewares=byzantine_auth
      - traefik.http.middlewares.byzantine_auth.basicauth.users=TODO


